mvc-spec/www.mvc-spec.org

src/index.md
I upgraded the Early Draft Release version to the current version of the API.
regards,
Daniel Dias
=> Upgrade version 1.0-edr1 to 1.0-edr2 .

src/_templates/page.html, src/mailing/mailing.html
I added the link to the new google groups discourse lists, and the java.net list was closed last week.
=> update mailing list.

src/learn/index.md, src/ozark/docs/install-javaee.md
I documented and tested the installation on wildfly 10/wildfly swarm and Glassfish/Payara. TomEE didn't work out of the box and I didn't want to go into the details of replacing cxf with jersey, as this would missing the point of an application server. I'll file an issue for CXF-support and look into it, shouldn't be to hard.
=> Install guide for Wildfly and Glassfish

src/spec/index.md
=> Update link for spec

src/logo/index.md
=> Fix minor typo

src/learn/index.md
this is a blog about our first mvc 1.0 sample application with imixs-workflow
=> new blog / tutorial about mvc 1.0

src/learn/index.md
- add an update in slide 
- add an talk in pt-br
=> add new Slide and my talk - pt-br.

src/learn/index.md
add ing new post about MVC 1.0 using Thorntail(old Wildfly Swarm) + template engine Thymeleaf
=> add new post.

src/ozark/docs/install-javaee.adoc, src/ozark/docs/install-servlet.adoc
this PR contains an small update of dependencies to run Ozark/Krazo in Tomee8/tomcat9 .
=> update dependencies to tomcat,tomee

src/learn/index.md
this PR contains update the links to blogs and an link to live code in pt-br
=> add new video and update links blog .

src/learn/index.md
=> small fix in link the video.

package.json, src/spec/index.md, src/spec/tck/index.adoc
Created a page with instructions for the TCK and issue reporting.
Still missing some details, but we can add them as we go...
=> Add page for TCK

src/learn/index.md
this PR contains an simple article of how use Eclipse Krazo with TomEE - M3
=> add new link post .

src/learn/index.md
new post about template engine
=>  new post about template engine

.travis.yml, package-lock.json, package.json, src/learn/index.md, src/logo/index.md
Updates all the node dependencies and fixes some minor rendering issues occurring with the latest markdown renderer.
=> Updated node packages + minor adjustments

src/learn/index.md
add new post about  Events and Kind of return to views .
=> add new post link.

src/learn/index.md
Add new apresentation about Eclipse Krazo to  Barranquilla JUG in Spanish made yesterday .
=> add new video in Spanish for Barranquilla JUG

src/learn/index.md
=> fix link in video in spanish

src/krazo/docs/install-servlet.adoc
=> Fix three typo's in the Install Guide for Servlet Containers

src/krazo/docs/install-servlet.adoc
Follow-up on eclipse-ee4j/krazo#80, this updates the docs accordingly.
=> Add metadata-complete="true" to sample web.xml

src/krazo/docs/install-archetype.adoc, src/krazo/index.md
I created a small archetype for generating MVC apps based on Jakarta EE 8. I think it might be a easier way for people to try the API and Krazo instead of using the current guides.
=> Archetype installation guide

conf/versions.json, src/krazo/docs/install-snapshots.adoc, src/news/2019-10-28-eclipse-krazo-beta1.md
This updates the version metadata and adds a news entry for the release
=> Update the site for 1.0.0-Beta1 release

src/learn/index.md
I extended my existing slides with some information about the security aspects of the MVC API. Also, there is a video of the latest talk now.
=> Add latest talk version and video

src/learn/index.md
=> add new article.

src/learn/index.md
lecture make in 2020/06/13  in PeruJug .
=> add lecture in PeruJug.
